# List of all available tests
TESTS ?= \
	Flowthrough_trans_periodic \
	Flowthrough_x_inflow_y_outflow

MAKEFILE_DIR := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))
include $(MAKEFILE_DIR)/Makefile.test

