LDFLAGS = -lrt -lgfortran -std=c++17 -Wl,-rpath=/proj/group/spacephysics/libraries/gcc/8.3.0/phiprof/lib:/proj/group/spacephysics/libraries/gcc/8.3.0/boost/lib:/proj/group/spacephysics/libraries/gcc/8.3.0/vlsv/lib:/proj/group/spacephysics/libraries/gcc/8.3.0/jemalloc/lib:/proj/group/spacephysics/libraries/gcc/8.3.0/zoltan/lib:/proj/group/spacephysics/libraries/gcc/8.3.0/papi/lib  

INC_DCCRG := -I/proj/group/spacephysics/libraries/dccrg

INC_FSGRID := -I/proj/group/spacephysics/libraries/fsgrid

INC_VECTORCLASS := -I/proj/group/spacephysics/libraries/vectorclass

INC_BOOST := -I/proj/group/spacephysics/libraries/gcc/8.3.0/boost/include
LIB_BOOST := -L/proj/group/spacephysics/libraries/gcc/8.3.0/boost/lib -lboost_program_options

INC_ZOLTAN := -I/proj/group/spacephysics/libraries/gcc/8.3.0/zoltan/include
LIB_ZOLTAN := -L/proj/group/spacephysics/libraries/gcc/8.3.0/zoltan/lib -lzoltan

INC_VLSV := -I/proj/group/spacephysics/libraries/gcc/8.3.0/vlsv
LIB_VLSV := -L/proj/group/spacephysics/libraries/gcc/8.3.0/vlsv -lvlsv

INC_SILO := -I
LIB_SILO := -L

INC_JEMALLOC := -I/proj/group/spacephysics/libraries/gcc/8.3.0/jemalloc/include
LIB_JEMALLOC := -L/proj/group/spacephysics/libraries/gcc/8.3.0/jemalloc/lib -ljemalloc

INC_PROFILE := -I/proj/group/spacephysics/libraries/gcc/8.3.0/phiprof/include
LIB_PROFILE := -L/proj/group/spacephysics/libraries/gcc/8.3.0/phiprof/lib -lphiprof

INC_PAPI := -I/proj/group/spacephysics/libraries/gcc/8.3.0/papi/include
LIB_PAPI := -L/proj/group/spacephysics/libraries/gcc/8.3.0/papi/lib -lpapi

INC_EIGEN := -I