name: C/C++ CI

on:
  push:
    branches: [ testsuite ]
  pull_request:
    branches: [ testsuite ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure -install
    - name: make
      run: make
    - name: test
      run: |
        cd testpackage && make
